QOL: Allow userfraction of 1.0
r0adkll/upload-google-play pull request #195
Opened 2023-09-27 18:46 UTC by MartenM

Allows a userFraction of 1.0 to be input by a user. Anything higher than 0 is still accounted for as invalid.

2023-09-27 23:01 UTC, boswelja requested changes

2023-09-27 23:01 UTC, boswelja commented on src/edits.ts
> +            options.userFraction = undefined;
Please at least add a warning that userFraction is ignored. I don't think we want people getting into a habit of passing data that won't be used

2023-09-27 23:01 UTC, boswelja commented on src/edits.ts
> +            options.userFraction = undefined;
It should also only be a warning for "completed" releases. We still want to fail on invalid config (partial rollout at 100% is invalid)

2024-01-10 21:14 UTC, boswelja commented
Hey @MartenM, are you still interested in working on this?

2024-01-12 10:13 UTC, MartenM commented
Ah sorry, I missed the feedback. Will check if I have some time later this week.

2024-02-07 11:23 UTC, boswelja commented
Hey @MartenM, did you get a chance to look at this again?

2024-02-08 09:50 UTC, MartenM commented
I have started working on my Masters's Thesis so my spare time has been limited quite a bit.
Feel free to close this draft if you want.

2024-02-08 12:11 UTC, boswelja commented
No worries, thanks for letting me know!

2024-02-08 12:12 UTC, closed without merging