changesNotSentForReview support
r0adkll/upload-google-play pull request #88
Opened 2021-11-12 18:39 UTC by princefr

We added support for changesNotSentForReview

2021-11-21 01:07 UTC, tannermares commented
Anything blocking this @r0adkll?

2021-12-02 22:15 UTC, Rukkaitto commented
I need this too @r0adkll

2021-12-30 11:42 UTC, AMSTKO commented
any news?

2022-01-12 20:44 UTC, yairm210 requested changes

2022-01-12 20:44 UTC, yairm210 commented on action.yml
> +    required: true
Adding a new "required" parameter will break all existing usages of this action.
This is probably one of the reasons this hasn't been accepted.
This should be changed to required:false, both here and below in main.ts, and the default value should enable the action to work as it has until now.

2022-01-12 20:44 UTC, yairm210 commented on README.md
> +  changesNotSentForReview: true
This doesn't make sense as an example usage. Draft shouldn't include userFraction as well. The draft should be a separate example.

2022-01-12 20:44 UTC, yairm210 commented on README.md
> +uses: swootte/upload-google-play@V1.1.5
The example usage of this repo won't have an example using another repo... and there's no reason to have it reference a specific subversion either

2022-01-12 20:44 UTC, yairm210 commented on action.yml
> +name: 'Upload Android application to Play Store'
What's the reason behind this change?

2022-01-12 20:44 UTC, yairm210 commented on src/main.ts
> +            changesNotSentForReview: JSON.parse(changesNotSentForReview),
The JSON parsing should be in the validation step - if this is malformed (unparseable) json, we should warn the user

2022-05-03 01:57 UTC, lozdan commented
@princefr any update about this?

2022-06-15 02:08 UTC, boswelja commented
@princefr are you still interested in working on this? If not, I'll take it over.

2022-06-15 02:09 UTC, boswelja commented
Closes #84

2022-06-18 07:37 UTC, boswelja commented
I have reimplemented this over on #117, closing this one.

2022-06-18 07:37 UTC, closed without merging